### ISSUE TITLE
Add video to About page

### ISSUE THREAD

**Issue by JonKusner** [razzius/hms-weave#10]
Upload tutorial video to end of help page. Include a link to the transcript, the text of which is below:

1. Welcome to Weave. This 4 minute tutorial will guide you in how to create a faculty profile.
2. First, begin by entering your name and preferred email.
3. You may complete the “Hospital Affiliations” section by typing an institution’s name, seen here with Cambridge Health Alliance. Or, you may click the dialogue box to view the drop down menu and select an institution. This logic of selection will be seen in many other sections below.
4. For the “Clinical Interests” and “Professional Interests” sections, you may select tags as you would with “Hospital Affiliations.” You may also create your own tags by typing out the tag and pressing the enter key.
5. In the “Parts of Me” section, there are no suggested tags. This is a section in which you may create tags that describe aspects of your identity that you would like to share with students and faculty on Weave. Some examples are provided here. Please feel empowered to share any personally meaningful information in this section.
6. For the “Activities I Enjoy” section, you may select tags or create your own tags. Here, we have created “scuba-diving” and “bungee-jumping,” which were not available in the previous list. For more information on how to create tags, please visit our “Help” page.
7. In this text box, you may share additional information with mentees.
8. On the top left hand side, you may upload an image from your computer or device by clicking “Choose file”. The image can then be cropped and adjusted before saving the image by clicking “Save image”.
9. Be sure to use the “I am available to mentor in the following ways” section to communicate any other opportunities that you are willing to offer mentees.
10. The cadence section allows you to demonstrate, on average, how often you would like to meet with mentees.
11. Click “Preview Profile” to see how your profile will appear on Weave.
12. You may at anytime adjust the “on/off” toggle for your profile. When “on”, the toggle will turn blue and this will allow your profile to be searched by mentees. When “off”, your profile will be hidden from others until you flip the toggle back to the “on” position.
13. When you are satisfied with how your profile looks, you may publish your profile! This is how your profile is saved in our system. If you would like to only save your profile and return to edit at a later time, please turn your “on/off” toggle to the “off” position and publish your profile.
14. To view your profile in the view that is searchable to students, navigate to the homepage and click on “Browse all faculty profiles.” You may scroll to find the snapshot of your profile. If you turn the toggle to “off” and refresh the page, your profile will not be viewable or searchable by students or faculty. When the toggle is “on” and the page is refreshed, your profile will be viewable again.
15. When you are finished, you may log out. 
16. Of note, for your security, you will be automatically logged off 1 hour after you initially log into Weave.
17. For additional questions, please visit our “Help” page or contact us at weave@hms.harvard.edu. Thank you.

**Comment by JonKusner** [comment]
We need to make decision about how password protected this is. One idea is to have a portion of the "Help" page that is behind password protection, prompts for log-in. This would be behind that along with other videos in the future.

**Comment by razzius** [comment]
Depends on https://github.com/razzius/hms-weave/issues/14

**Comment by razzius** [comment]
Once the help page is HTML, we can password-protect the video.

**Comment by jjchen20** [comment]
Jon and I will ask early adoptee faculty if they would be comfortable having their names and clinical/professional interests shown in the Help tutorial (Oct 2018 version).

**Comment by jjchen20** [comment]
Let's add the new video for the MMS IT award to the Help page instead. I will edit the video beginning and ending when I have a little more time, hopefully at the end of December.

**Comment by jjchen20** [comment]
The video content describes Weave in addition to its components. May be more useful on the About page.

**Comment by jjchen20** [comment]
Video added to Drive folder, ready for uploading to website on "About" page, underneath the text for "Where Can I Learn More About Weave?"

**Comment by jjchen20** [comment]
Is there a way to change the video preview image to this one:
![image](https://user-images.githubusercontent.com/43801169/73230416-3245a880-414b-11ea-8c90-a9588662321d.png)

Can we remove the gray borders around the video? The tutorial video on the login page is just the video, which looks a cleaner.

**Comment by razzius** [comment]
Good call. Removed the border and changed the thumbnail, by uploading to youtube under admin@hmsweave.com.

**Comment by jjchen20** [comment]
Great, thank you. I thought it was possible to just select a frame from the video as the thumbnail.

Can we do this image instead (no arrow in the top right corner):
![image](https://user-images.githubusercontent.com/43801169/73302475-b1d28680-41e2-11ea-8054-02857e3a9b36.png)

**Comment by razzius** [comment]
Updated the thumbnail
