### ISSUE TITLE
Expand verification token duration to 2 weeks

### ISSUE THREAD

**Issue by jjchen20** [razzius/hms-weave#100]
When logging in for first time, pop-up screen should ask: "Are you logging in on a personal device?" If yes, allow verification token duration to be 2 weeks. If no, verification token will expire after 1 hour.

**Comment by jjchen20** [comment]
Default should assume that it's on a public device, unchecked for "Are you logging in on a personal device?"

**Comment by razzius** [comment]
This is live on staging (hms-weave-staging.herokuapp.com)

**Comment by razzius** [comment]
Looks like it's working so I pushed to production with 4f425f9cdb4a1c7d796bb486bb12905c9dcf8c52
