### ISSUE TITLE
Add the HMS and HSDM crests to the page header, to the left of "Weave"

### ISSUE THREAD

**Issue by jjchen20** [razzius/hms-weave#102]
HMS:
![image](https://user-images.githubusercontent.com/43801169/60229136-dccab580-9862-11e9-8a2e-3843b38df3f7.png)

HSDM:
![image](https://user-images.githubusercontent.com/43801169/60229150-ef44ef00-9862-11e9-9351-27bb31e65010.png)

**Comment by razzius** [comment]
Check https://hms-weave-staging.herokuapp.com/

**Comment by jjchen20** [comment]
I like the positioning and size of the crests. The images are a bit blurry
though. Can we use any higher resolution images?

**Comment by jjchen20** [comment]
I think copy and pasting the images into Github may have reduced their quality. 
Here are the image links: 
https://en.wikipedia.org/wiki/Harvard_Medical_School#/media/File:Harvard_Medical_School_shield.svg
https://en.wikipedia.org/wiki/Harvard_School_of_Dental_Medicine#/media/File:Harvard_School_of_Dental_Medicine_shield.svg

**Comment by razzius** [comment]
Thanks for the svg links. I updated staging; here's a screenshot

![image](https://user-images.githubusercontent.com/2244895/64756122-8d4f6980-d4e2-11e9-9685-4ba7ec1526cb.png)

Strangely the colors are slightly different but I think that's ok. If that looks good to y'all @jjchen20 	@JonKusner 	I'll update weave.hms.harvard.edu.

**Comment by jjchen20** [comment]
Looks good, go for it!

**Comment by razzius** [comment]
Done
