### ISSUE TITLE
Internet Explorer interface: Submit button is compressed

### ISSUE THREAD

**Issue by jjchen20** [razzius/hms-weave#108]
![image](https://user-images.githubusercontent.com/43801169/63657982-ea25f280-c774-11e9-9b0d-7c525b5189f0.png)

**Comment by razzius** [comment]
![image](https://user-images.githubusercontent.com/2244895/64318142-f97c1b80-cf7e-11e9-8420-70c14646b46c.png)

In IE10 this is not an issue. Not sure how to debug this...

**Comment by jjchen20** [comment]
The hospitals may run on Internet Explorer 11 and not 10. I can check this again the next time I'm in the hospital.
