### ISSUE TITLE
"Show 20 more" for search page

### ISSUE THREAD

**Issue by JonKusner** [razzius/hms-weave#11]
Implement a "show 20 more" button at the bottom of the search page. Similar to that of Google scholar.

**Comment by JonKusner** [comment]
We now have 76 faculty profiles; this would be very nice to implement.

**Comment by razzius** [comment]
This is done. In the current implementation, it loads 20 more as you scroll down.

**Comment by JonKusner** [comment]
I am going to reopen this just to include two buttons at the bottom: "show 20 more" and "back to top". This is looking great, good job.

**Comment by razzius** [comment]
Done
