### ISSUE TITLE
Bug in search/filter routing: Search only works if a degree is selected

### ISSUE THREAD

**Issue by jjchen20** [razzius/hms-weave#113]
Students and faculty should be able to use the search feature without any filters on

![image](https://user-images.githubusercontent.com/43801169/64747254-77d74100-d4dc-11e9-8649-2fa3abfb020f.png)

![image](https://user-images.githubusercontent.com/43801169/64747286-8de50180-d4dc-11e9-8de8-8ae437d0943f.png)

**Comment by razzius** [comment]
This should be fixed. Let me know if it's still an issue @jjchen20

**Comment by razzius** [comment]
(on both staging and master)
