### ISSUE TITLE
Login security token

### ISSUE THREAD

**Issue by jjchen20** [razzius/hms-weave#117]
Navigating away from the website, even after clicking on "This is a personal device (stay logged in for 2 weeks)," leads to immediate logout. People who click on "stay logged in for 2 weeks" will expect that even if they close the website and come back to it, that there will be memory of their having logged in. I am noticing that the tokens indeed do work for up to 2 weeks (on any device - I've tried the same token on 3 different computers and wifi networks at the hospital and on campus and they've all worked/ not been specific to my personal device), but it requires having saved the token and clicking on it to start each session, instead of having the personal device be remembered when directly navigating to the Weave homepage. From a practical use standpoint, most people will not save the token email, or may have trouble locating that email if it gets buried under other emails. Is there a solution where the personal device is truly recognized and stays logged in without the website continuously open?

**Comment by jjchen20** [comment]
I'm reopening this issue because after navigating back to the Weave homepage, I'm now logged out. It's been about 1 hour since I logged in. I had clicked on a 2-week token generated on 9/10 for my initial login from my email.

**Comment by jjchen20** [comment]
The 2-week login is still not working for me, even within the hour, on the same browser, connected to the same wifi network.

**Comment by razzius** [comment]
Relates to https://github.com/razzius/hms-weave/issues/146

**Comment by razzius** [comment]
Likely causes:
https://github.com/razzius/hms-weave/issues/171
#146
