### ISSUE TITLE
Tag generation Issues

### ISSUE THREAD

**Issue by jjchen20** [razzius/hms-weave#120]

**Comment by jjchen20** [comment]
In the faculty profile generation section

**Comment by jjchen20** [comment]
What should create a new tag:
- Clicking away from what's been typed so far (should create the tag instead of deleting it)
- Comma, semi-colon, and periods should create separate tags

**Comment by razzius** [comment]
2 hours dev work

**Comment by razzius** [comment]
Took about 4 hours, though I got distracted in the process. Testable on staging

**Comment by razzius** [comment]
I think making periods create separate tags could lead to issues, if for example if somebody wanted to put [".hack fan"](https://en.wikipedia.org/wiki/.hack) or any other tag that has a period in it, this would prevent the tag from being created.

For what it's worth, currently no tags exist in the database with periods, so it's a somewhat rare case.

**Comment by jjchen20** [comment]
This looks good on staging and ready to deploy. Outlining here what creates the tag:
- Clicking on the pre-made tag highlighted
- Clicking anywhere on the page or in another text box
- Pressing the tab key
- Pressing the enter key
- Typing a comma
- Typing a semi-colon

The search feature (#124) should also allow typing/ searching for tags using all of the options above.

**Comment by jjchen20** [comment]
Can we apply the tag generation capabilities universally across all the tags (not just the open-ended ones)?

Typing in comma or semi-colon did not create/select the tag automatically for the academic degrees:
![image](https://user-images.githubusercontent.com/43801169/65990325-5e7d4100-e459-11e9-9ddf-42277f5ba06c.png)

**Comment by jjchen20** [comment]
Comma and semi-colon tag generation currently works for "Parts of Me" and "Activities I enjoy" but not "Academic Degrees," "Institutional Affiliations," "Clinical Interests," and "Professional Interests." Same rules across all tag generation will be more intuitive for users.

**Comment by razzius** [comment]
I added comma / semicolon / click elsewhere = complete for all creatable tags, which is everything but institutional affiliations. Since users cannot create institutional affiliations, I think it makes sense to have them select the affiliation via click, tab, or enter, and to discard something typed without a matching affiliation and they click elsewhere. Open to feedback on this.

**Comment by jjchen20** [comment]
That makes sense to me too. See #135 for similar conversation, with bug of menus staying open only after comma/semicolon tag creation.

**Comment by razzius** [comment]
Also see #136
