### ISSUE TITLE
Update Help page: Add Edge as supported web browser

### ISSUE THREAD

**Issue by jjchen20** [razzius/hms-weave#122]

**Comment by jjchen20** [comment]
If yes, change the Help page wording to reflect that Edge is a supported web browser

**Comment by jjchen20** [comment]
Edge is a supported browser. Added to Help page, needs to be fixed here: 0ec66285064a8329a83503c43dab3624e205ab56.

**Comment by razzius** [comment]
Excuse that my automated tests are currently broken and won't deploy this change. I'll look into this sometime today.

**Comment by jjchen20** [comment]
Will the change deploy automatically once the automated tests are fixed? Feel free to go ahead and deploy this change once everything is working again.

**Comment by razzius** [comment]
Deployed.
