### ISSUE TITLE
Hyperlinks should open new tabs instead of redirecting to the website

### ISSUE THREAD

**Issue by jjchen20** [razzius/hms-weave#126]
Clicking on a hyperlinked url should open a new tab instead of pulling up the new webpage directly, so people can continue scrolling/ reading without losing their place. This should apply to: 1) linking to another page in Weave (i.e. Help or Resources), 2) linking externally to another website.

**Comment by razzius** [comment]
In my opinion, it makes sense to open external links in new tabs, but navigation within the site should stick to the same tab. This is what I've implemented for now; we can discuss the benefits and drawbacks of internal links opening in a new tab later (or just post your thoughts here @jjchen20).

**Comment by jjchen20** [comment]
Opening both external and internal links in a new tab (as now implemented)
allows people who are reading through the expectations carousel (when they
click on reading more for resources) not to lose their place. Same for the
"Help" page from the profile generation. Though less of an issue if there
is a message warning that they have unsaved data when they attempt to
navigate away from the profile generation page.
