### ISSUE TITLE
Annual email to faculty to update their profile

### ISSUE THREAD

**Issue by JonKusner** [razzius/hms-weave#13]

**Comment by JonKusner** [comment]
Hello,

This is an annual email from Weave (hyperlink this), a mentorship platform that connects students and faculty at Harvard Medical School. Our records indicate that you have a mentor profile on Weave. Each year we ask faculty mentors to revisit and update their profile; this way students are searching an accurate and up to date list of faculty mentors. Some faculty may not have time to take on mentees; in that case, we ask mentors to go into their profile and change their status to unavailable for mentoring by using the "on/off" toggle at the top of the page. This process is further explained on our help page: https://weave.hms.harvard.edu/help. Please reach out to our team with any questions. Thank you for your energy in maintaining Weave and in continuing to allow for high quality student-faculty mentoring at Harvard Medical School. 

Sincerely,

HMS Weave Team



We may also develop some mechanism to make profiles turn off after ~1-1.5 years of inactivity but we will deal with that problem later, after we have a lot of faculty on board.

**Comment by razzius** [comment]
Since the emails would be from the admin gmail anyways, for now, we can email out manually. Features like deactivating profiles after inactivity can come later. @JonKusner 	how do you feel about this issue becoming: "Allow exporting csv of emails"?

**Comment by jjchen20** [comment]
@razzius Exporting CSV of emails then emailing separately is good. I manually exported emails for faculty today, would be good to automate the process. We could email from the HMS Weave account for sustainability.

**Comment by razzius** [comment]
There's a mode report for this here: https://modeanalytics.com/editor/rerere/reports/dff0b26db30c
