### ISSUE TITLE
Loading speed of all faculty profiles

### ISSUE THREAD

**Issue by jjchen20** [razzius/hms-weave#134]
What are different variables that go into how fast the profiles load? I've been having slow loading speeds today for the past few hours and I'm directly connected via an Ethernet. Other sites load quickly for me. Is this a server issue? What happens if many people try to access the site at one time? Is there a traffic limit at a given point in time?

**Comment by razzius** [comment]
Here are some of the metrics that I have visibility into, from the server side (big image, recommended to click to view the image outside of comment):

![image](https://user-images.githubusercontent.com/2244895/67224121-6b041200-f3e5-11e9-82a3-f443acf81ca4.png)

"Response time" is the key one here; in the past 24 hours the slowest response has been about 250 ms, which is still likely to be fast enough to provide a good user experience. Other metrics look healthy as well; memory usage is constant and low and dyno load (a proxy for compute demand) is low. Of course, throughput is low over the past 24 hours (Sunday) and the more users request the service at the same time, the slower everything will be.

There is no currently-enforced traffic limit, so if there's a traffic spike it'll just get slower for everybody, and if a request has been waiting for 30 seconds, it will time out.

I don't have any metrics on the load time from 20 days ago, but if you notice this again, let me know and I'll take a look at the metrics at that point in time. I can also give you access to view the metrics @jjchen20 if you're interested.

**Comment by jjchen20** [comment]
Thanks for sharing the metrics, @razzius. 250 ms is an acceptable speed. On occasion, I have encountered much slower speeds compared to other sites, especially when waiting for all faculty profiles to load on the "browse faculty profiles" view. If you can give me access to view the metrics, I can pull them up in real-time if I encounter slow loading issues in the future.
