### ISSUE TITLE
Completing tags by clicking on them, tab, or enter should make tag uppercase

### ISSUE THREAD

**Issue by razzius** [razzius/hms-weave#136]
In parts of me, type "asdf", click on it.

Observe "asdf" is created, when "Asdf" would be expected.

**Comment by JonKusner** [comment]
This looks really good, some minority hilarious behavior: 1. if you type "sdf" it does not offer to creat the tag. 2. When there is a list of options, I was not able to arrow key through the options

**Comment by JonKusner** [comment]
Oh no never mind on the 'sdf' stuff, I had that tag twice.

**Comment by jjchen20** [comment]
The autocapitalization is working for me. Looks good!

**Comment by jjchen20** [comment]
Hey Razzi - Can we make the autocapitalization present for the search feature too?
![image](https://user-images.githubusercontent.com/43801169/68505251-c2eba700-0234-11ea-993c-ec2380bc6e6e.png)

**Comment by razzius** [comment]
Not going to implement autocapitalization for search - it's case-insensitive search and I think the behavior would be unintuitive for users.
