### ISSUE TITLE
Add "date last updated" to the faculty profile

### ISSUE THREAD

**Issue by jjchen20** [razzius/hms-weave#143]
Will make it easier to identify how recently a faculty has created or updated their profile.

**Comment by razzius** [comment]
Looks like this 
![image](https://user-images.githubusercontent.com/2244895/71209389-0a704480-2271-11ea-9843-7d7589ecdc52.png)

**Comment by jjchen20** [comment]
Looks good! Thanks! Is there a way for the admin to select whether any
changes on the admin end should be reflected in the profile last updated
date? I am imagining we may want to edit capitalization, but not want the
date to change. Or, if we help a faculty make a change, we may want that
content change to be reflected in the last updated date.

**Comment by razzius** [comment]
Good point @jjchen20. Currently editing through the admin will not cause the date updated to change but if you click "edit profile as admin" it will. I can update it to not update the last updated date in both of these cases.

**Comment by jjchen20** [comment]
Ready to deploy. It looks like "edit profile as admin" still changes the last updated date.

**Comment by razzius** [comment]
This is now fixed so that admin edits will not update the last updated date.
