### ISSUE TITLE
Sort by hospital - enhance aesthetics of box size

### ISSUE THREAD

**Issue by jjchen20** [razzius/hms-weave#144]
The hospital sorting box is larger than the other two. Can we make them all the same height for aesthetic purposes?

![image](https://user-images.githubusercontent.com/43801169/71020195-b880c080-20b0-11ea-85cb-c7808739e908.png)

**Comment by razzius** [comment]
I'm making it so that you can only sort by one hospital at a time. Previously you could add multiple hospitals and it would find users with both hospital affiliations, but there are likely to be so few profiles matching such queries, it does not seem useful.

**Comment by jjchen20** [comment]
Great, that makes sense for the hospitals. That's probably how most people
are using that functionality right now.
