### ISSUE TITLE
Idea: new less-dense font

### ISSUE THREAD

**Issue by razzius** [razzius/hms-weave#156]
![image](https://user-images.githubusercontent.com/2244895/72852719-4a598b80-3c64-11ea-9851-c610a4da3879.png)

On the left is the current font, on the right is what it could be (Apple / Microsoft system font)

**Comment by razzius** [comment]
Take a look at this on staging and let me know what you think.

**Comment by JonKusner** [comment]
Love

**Comment by jjchen20** [comment]
The new font is beautiful! Let's change it across the entire platform! For
the expectations, resources, and help pages too.

**Comment by razzius** [comment]
Yep, it'll be everywhere.
