### ISSUE TITLE
Unecessary comma on FAQ help page

### ISSUE THREAD

**Issue by Chronowork1** [razzius/hms-weave#166]
> Weave is compatible with Chrome, Safari, Edge, Mozilla Firefox, and Internet Explorer 10. We recommend using Chrome, Safari, Edge, or Mozilla Firefox web browsers, to create or view profiles with the optimized interface experience.

Extra comma after "Mozilla Firefox web browsers,".

**Comment by Chronowork1** [comment]
The extra comma after "Mozilla Firefox web browsers" is removed from staging.

**Comment by razzius** [comment]
Deployed!
