### ISSUE TITLE
COVID19 informational banner + page

### ISSUE THREAD

**Issue by razzius** [razzius/hms-weave#180]
Will use a new announcements feature

**Comment by jjchen20** [comment]
CDC website: https://www.cdc.gov/coronavirus/2019-ncov/index.html

**Comment by jjchen20** [comment]
During the current COVID-19 pandemic, we are encouraging mentor and mentee pairs to meet over Zoom. All Harvard students and faculty receive free Zoom access available at: https://harvard.zoom.us/ This recommendation will remain active throughout the COVID-19 pandemic. More information can be found on the CDC’s website: https://www.cdc.gov/coronavirus/2019-ncov/index.html

**Comment by razzius** [comment]
Only on home page. Goes where internet disconnected message goes.
