### ISSUE TITLE
Get rid of autocomplete message "Create ..." for parts of me

### ISSUE THREAD

**Issue by razzius** [razzius/hms-weave#185]
There is no looking up of tags in this section, so we do not need a "Create ..." option. Or, if we keep it around, it should capitalize the first letter, as happens when clicked.

**Comment by razzius** [comment]
![image](https://user-images.githubusercontent.com/2244895/77686960-f49ea980-6f5a-11ea-8588-4ba25601ef5f.png)

**Comment by jjchen20** [comment]
For standardization, I think we should keep the word create in front of the
new tag. I agree with auto-capitalization of the first letter.

**Comment by jjchen20** [comment]
Recommend leaving as is. Auto-capitalization of first letter is working.
