### ISSUE TITLE
Background of log out

### ISSUE THREAD

**Issue by JonKusner** [razzius/hms-weave#2]

**Comment by JonKusner** [comment]
Make the default background for the logout notification specific to the role of the user (i.e. student v. faculty)

**Comment by razzius** [comment]
What do you mean default background? What url is it on?

**Comment by jjchen20** [comment]
http://weave.hms.harvard.edu/

**Comment by JonKusner** [comment]
Sorry I know I posted this error but Jane was really the one who found it. My understanding was that when she was logged in as a faculty member, at one point she left the session on for an hour and was prompted with a logout notification, when this occured (if I remember correctly) the background page for some reason was the student homepage.
I have left a session on in order to get the logout notification and for me the background page was whatever page I was on; it did not reroute to any apparent "default" background page. Jane could you help clarify?

**Comment by jjchen20** [comment]
The logout notification worked for me yesterday when I left a session open
for a few hours, though only when I navigated around the website with a few
clicks and going to other pages. Can we have the logout notification come
up at the point when the logout occurs? Someone could conceivably leave the
faculty profile open, complete it after the logout time, but not get the
notification until they try to save their profile and get frustrated that
they have to input their information all over again.

The background page I was talking about was a half-loaded screen with the
logout notification that sometimes occurs when I first navigate to the
website for the day. Razzi, you had mentioned this might have to do with
the cache. It hasn't happened for me in the past couple days. We can
resolve this as an issue.
