### ISSUE TITLE
Disability services office link update needed on Weave

### ISSUE THREAD

**Issue by razzius** [razzius/hms-weave#23]
> Yesterday, a new disability services office launched for HMS/HDSM and Yolanda Paul is no longer in a role that serves students with disabilities.
> 
> Here are new helpful links you might choose to use on the help page.
>  
> https://meded.hms.harvard.edu/student-resources-accessibility
> 
> https://meded.hms.harvard.edu/disability-services

**Comment by jjchen20** [comment]
Thanks Razzi. I just updated the "Website Language" Google Doc with the new info in the Resources section (pg 4-7).
