### ISSUE TITLE
Intellectual property/ copyright

### ISSUE THREAD

**Issue by jjchen20** [razzius/hms-weave#26]
Example terms and use language: https://ratearesidency.com/terms-and-conditions/

**Comment by JonKusner** [comment]
My buddy also said that we should look into copyleft, a play off of copyright (https://en.wikipedia.org/wiki/Copyleft). It looks a lot like what we are looking for; we would now need to find a copyleft license with the correct language/similar language for our purposes.

**Comment by jjchen20** [comment]
FYI, we advertise Weave as open source in the Roadmap section, and we're getting a fair number of website hits from around the world and people emailing to ask about expansion of the website. I think figuring out the intellectual property stuff is a high priority for this month.

**Comment by razzius** [comment]
Seems to me we're at a stable spot with the MIT license with our names and CITATION.md.

**Comment by jjchen20** [comment]
Example language from an open source webpage: http://www.cbioportal.org/

The cBioPortal for Cancer Genomics provides visualization, analysis and download of large-scale cancer genomics data sets.
Please cite Gao et al. Sci. Signal. 2013 & Cerami et al. Cancer Discov. 2012 when publishing results based on cBioPortal.

**Comment by jjchen20** [comment]
Do we need to register the license? https://opensource.org/approval

**Comment by jjchen20** [comment]
FYI, the MIT license boiler plate includes: Copyright (c) [year] [fullname].  Do we want to add 2017 to the license folder?

Also, this article share how to generate a doi via Zendo so other people can cite the code: https://guides.github.com/activities/citable-code/

**Comment by razzius** [comment]
The https://opensource.org/approval process is for declaring a new license - say we came up with a new license "Weave License" - then we'd submit it to opensource.org.

**Comment by jjchen20** [comment]
Got it. If that's the case, we can close this thread.

**Comment by jjchen20** [comment]
Another example: https://depmap.org/portal/terms/

**Comment by jjchen20** [comment]
More example privacy use language: https://medschoolinsiders.com/privacy-policy/
