### ISSUE TITLE
Format email address so that it doesn't run into the clinical interests/professional interests etc. on the right hand side

### ISSUE THREAD

**Issue by jjchen20** [razzius/hms-weave#27]
Can we adjust the font of the email address so it doesn't run into the clinical interests on the right hand side? I've screenshotted a portion of the profile to protect faculty privacy. Boston Children's Hospital has particularly long email addresses (i.e. full name@childrens.harvard.edu).
![image](https://user-images.githubusercontent.com/43801169/47128102-d2bcd580-d244-11e8-9ca1-c53d9549ff24.png)

**Comment by razzius** [comment]
I made it so emails wrap around if they get too long (the email link itself is the full email, and unchanged)

![image](https://user-images.githubusercontent.com/2244895/50556412-77747e00-0c9e-11e9-8fa0-8e7aafff062f.png)

Additionally I believe some reformatting has given the left column more space so an email that's long enough to wrap is probably pretty long now.

**Comment by jjchen20** [comment]
What you've included above looks good and ready to deploy. I just checked the live website and there's still the problem with text running into the second column.

**Comment by razzius** [comment]
Deployed
