### ISSUE TITLE
Improve the mobile user interface

### ISSUE THREAD

**Issue by jjchen20** [razzius/hms-weave#31]
The profile creation page does not fit well on the mobile screen and the order of items does not flow particularly well at the moment, which could be something dissuading faculty from signing up from their phones.

**Comment by jjchen20** [comment]
The mobile interface looks 1000x better! If the FAQ page could be aligned like the other pages, that would be even better. The "Browse Faculty" view looks a little clunky in portrait mode on the phone, but looks good in landscape mode. Hopefully people are motivated to try tilting their phones to get a better view.

**Comment by razzius** [comment]
Browse faculty has been upgraded to work better on phones

**Comment by razzius** [comment]
One outstanding issue is that single faculty profiles collapse to 1 column when being viewed, but their name is in the right column which isn't visible until the user scrolls down.

### Current

Image
contact
optional expectations
name
affiliations
...

### Ideal

Image
Name
contact
optional expectations
affiliations
...

**Comment by razzius** [comment]
I'm going to close this and open a new issue for the mobile profile view order, without the high priority label. Feel free to add the high priority label to that if it seems worthy.
