### ISSUE TITLE
Future enhancement ideas - Brainstorming

### ISSUE THREAD

**Issue by jjchen20** [razzius/hms-weave#37]
Starting a place for brainstorming/ list of ideas for possible future enhancements, which we can separate out into separate issues if we decide to move forward with something:
1) Include tallies of hospitals/ specialties/ identities/ personal interests represented for students to see. Visual demonstration of diversity.
2) Pictoral demonstration/ word cloud of the "Parts of Me" and "Additional information" sections. Also to demonstrate diversity of perspectives/ experiences.
3) Develop a student portal to save "favorite" faculty profiles.
4) Keep track of the # of times profiles are viewed/ which terms are searched for most often.
5) Develop resident mentoring flow.
6) Design alumni mentoring flow.

**Comment by jjchen20** [comment]
7. Feature mentor/mentee stories in a new section, "Stories." Could be a once every couple months highlight.
8. For faculty development, we could share ideas for engagement/ building skills. I.e. Med Ed Day workshop, interviews with veteran faculty mentors. "Faculty Development" might be a separate section within the faculty log in portal.

**Comment by razzius** [comment]
Thanks for sharing your ideas here @jjchen20. I think having a way to set/update a message on the homepage and some sort of blog/news integration would be nice (7 above).

Aside: I see you added more lines as a comment - if you click the `...` menu at the top you can edit your original issue.

I'm going to close this to keep the open issues actionable. You can keep using it. We can also set up a separate ideas board.

**Comment by jjchen20** [comment]
Moth/story hour: Students and mentors could submit their stories every 6 months, which could be featured on the website --> user engagement.

Cons: Human capital required to moderate/ maintain posting of the stories.

**Comment by jjchen20** [comment]
9. Create a "Spotlight" page to feature community groups once a month to highlight diversity of identities and interests, i.e. Joint Committee on the Status of Women, Global Surgery Student Association
