### ISSUE TITLE
Faculty unable to add photo to profile

### ISSUE THREAD

**Issue by jjchen20** [razzius/hms-weave#40]

**Comment by razzius** [comment]
@jjchen20 	could you put the steps you believe the faculty took? Is there an email or fullstory for this?

**Comment by jjchen20** [comment]
From a faculty on 11/16/18 @ 3:15pm: "When I try to upload a photo, it won't upload. Any suggestions? Thanks!"

**Comment by razzius** [comment]
Duplicate of #33
