### ISSUE TITLE
Mobile faculty profile view

### ISSUE THREAD

**Issue by razzius** [razzius/hms-weave#41]
Notice that the optional expectations come before the name in this screenshot:

![image](https://user-images.githubusercontent.com/2244895/49336330-ca321b80-f5b4-11e8-826d-f9cd64c8a81d.png)

Single faculty profiles collapse to 1 column when being viewed, but their name is in the right column which isn't visible until the user scrolls down.

Current:

Image
contact
optional expectations
name
affiliations
...

Ideal:

Image
Name
contact
optional expectations
affiliations
...

**Comment by jjchen20** [comment]
Hey Razzi, the individual profiles look good and ready to deploy. The
browse faculty view on mobile looks a little messy with the right aligned
cadence and checkboxes. Is it possible to make cadence and checkboxes left
aligned like everything else in mobile view only? Also, there's a clear
rectangle underneath your picture that's not in any other profile previews.
Can you make the rectangle disappear?

**Comment by razzius** [comment]
Confirmed that panning the image works on mobile.

I have experimented with adding labels to the profile results so that the it's apparent what the checkboxes mean.

Here's how it looks on desktop:

![image](https://user-images.githubusercontent.com/2244895/50576969-0be7f900-0de3-11e9-8323-e732fb9addfa.png)

And mobile:

![image](https://user-images.githubusercontent.com/2244895/50576985-916ba900-0de3-11e9-9112-47f9dd99e7ab.png)

**Comment by jjchen20** [comment]
I'm a fan of the prior checkboxes only for the desktop view. We had wanted to created an icon that was informative and easy on the eyes. The explanation of the checkboxes sort of takes away from that effect. If we want to explain the checkboxes and cadence, we could include a static example profile at the top, before the faculty profiles.

In the mobile view, is there a way to hover/ expand on the checkboxes?

**Comment by razzius** [comment]
We could make it so that tapping a checkbox shows a tooltip, like hovering over the "available for mentoring" slider (screenshot below). I'll give that a go.

![image](https://user-images.githubusercontent.com/2244895/50605610-58394480-0e88-11e9-8e26-d5b91ee0f0e6.png)

**Comment by razzius** [comment]
I have made it so that the checkboxes can be tapped on mobile, which will show a tooltip for what they mean.

@JonKusner 	@jjchen20 	when you two get a chance, please test on https://hms-weave-staging.herokuapp.com and if it looks good [I'll merge to master](https://github.com/razzius/hms-weave/pull/50).

**Comment by razzius** [comment]
Deployed
