### ISSUE TITLE
"Preview profile" freezing

### ISSUE THREAD

**Issue by jjchen20** [razzius/hms-weave#43]
From a faculty member: Do you know if anyone has been able to successfully create a profile? I went through the email registration as directed, then I just tried 2 different times and when it gets to Preview Profile the website just basically freezes.  Just wondering if it’s a browser issue. I’m creating it from a desktop at BIDMC.

**Comment by razzius** [comment]
Confirmed that this happens in Internet Explorer 11 on Windows 7

**Comment by razzius** [comment]
The issue has been fixed and tested using https://www.browserling.com.
