### ISSUE TITLE
Expectations screen formatting

### ISSUE THREAD

**Issue by jjchen20** [razzius/hms-weave#46]
https://app.fullstory.com/ui/CZ9MQ/session/5662239398821888:5662239398821888!5629499534213120

This is what came up in the carousel for one faculty member yesterday: 
![image](https://user-images.githubusercontent.com/43801169/50248483-11c7ee00-0390-11e9-919d-11ff64a08f69.png)

The help page in the same session was also completely blank.

**Comment by jjchen20** [comment]
That's what's live on the student and faculty sides at the moment and showing up for me too. Not sure what happened but this is a pretty major issue.

**Comment by razzius** [comment]
Fixed
