### ISSUE TITLE
Remove duplicate email addresses from the verification email list in the admin view

### ISSUE THREAD

**Issue by jjchen20** [razzius/hms-weave#52]

**Comment by razzius** [comment]
Could you add a screenshot of how this looks, and explain why it's an issue?

What you might be seeing is that each login creates a record, but we want to keep track of those for auditing purposes (at least until we run out of database space)

**Comment by jjchen20** [comment]
To protect the privacy of users, I am omitting the screenshot. From the "Verification Email" (not Verification Token) page, I copy pasted all of the user emails page by page into an Excel spreadsheet, since we do not have a way to download a CSV of this information at the moment. There were a few duplicate emails that came up when I did it this way. It's been a while, and I manually deleted the duplicate emails and am not sure which ones they were anymore. Do you want me to provide the emails separately?

More important than this issue are related issues #66 , #6 , and #63 .

Here's a screenshot from the relevant portion of #6 
![image](https://user-images.githubusercontent.com/43801169/54794897-38f8ba80-4c20-11e9-9788-c88ac735daf8.png)

**Comment by razzius** [comment]
I don't think anything here is an issue any more. @jjchen20 correct me if I'm wrong.
