### ISSUE TITLE
Add allowable email domains

### ISSUE THREAD

**Issue by jjchen20** [razzius/hms-weave#53]
Add @hsdm.harvard.edu as a valid domain

**Comment by razzius** [comment]
Done

**Comment by jjchen20** [comment]
Add the following as valid email domains:
@forsyth.org
@post.harvard.edu
@tch.harvard.edu
@gse.harvard.edu

Include a link underneath the text box, above "Send verification email" on the registration page that links to "How does the email authentication work?" on the Help page.
![image](https://user-images.githubusercontent.com/43801169/56242369-fd011b80-604c-11e9-889c-9123b5ad399c.png)

**Comment by razzius** [comment]
I have updated the valid domains. Linking to a specific question on the help page is blocked by #14

**Comment by jjchen20** [comment]
Thanks Razzi. Can we include the allowable email domains underneath the "Send verification email"? I think that has been a point of confusion for some faculty who want to register with non-Harvard emails, with affiliations that have not yet come to our attention. I'll update the Help page now with these additional valid domains.

**Comment by razzius** [comment]
![image](https://user-images.githubusercontent.com/2244895/56383190-25fcea00-61ce-11e9-984b-c730f690e6b6.png)

Could look like this

**Comment by razzius** [comment]
![image](https://user-images.githubusercontent.com/2244895/56383388-88ee8100-61ce-11e9-8f21-7aa2da0ed6de.png)

**Comment by razzius** [comment]
Here's how it looks with a link to the help page

![image](https://user-images.githubusercontent.com/2244895/56387484-41212700-61d9-11e9-9a3d-8ce6bc95aeca.png)

It's not really blocked since email validation is the first thing anyways

**Comment by jjchen20** [comment]
Looks good! A couple edits:

Forsyth.org is listed twice. We can remove one of them.

I think we should also remove @hmsweave.com. No one outside of us will have
an email address at that domain.

Let's add "please" in front of "email us."

Can we capitalize "Help"?

**Comment by razzius** [comment]
Done
