### ISSUE TITLE
Notify users that they have unsaved data if they attempt to navigate away from edit profile

### ISSUE THREAD

**Issue by razzius** [razzius/hms-weave#55]
Especially when previewing a profile, it looks like it's already saved. Make it alert the user so they can choose to not close the page.

**Comment by jjchen20** [comment]
The highlighted "Save profile" at the bottom after making edits is helpful:
![image](https://user-images.githubusercontent.com/43801169/51791434-eeebdf00-2170-11e9-8cc3-df2a2226a728.png)

A pop up notification alert would make this more safe so faculty don't spend a really long time making a profile or edits and nothing saves if they navigate away.

**Comment by jjchen20** [comment]
This did not work for me from either the preview profile or the profile generation page. I navigated away to the home page and to the resources page and there were no pop up notifications or warnings about unsaved data.

**Comment by razzius** [comment]
Note: this is because of react-router links

**Comment by JonKusner** [comment]
This worked very well for me, well done!

**Comment by jjchen20** [comment]
When I tried to click "Save profile," the navigation away pop up showed up as well. The pop up should only show up for clicks away from the page.
