### ISSUE TITLE
Add "hospital medicine" as a pre-set clinical tag

### ISSUE THREAD

**Issue by jjchen20** [razzius/hms-weave#56]
Requested by a faculty member.

**Comment by JonKusner** [comment]
I tried doing this through the Admin interface by making a new taking and setting it to public. It didn't seem to appear when I tried to test it.

**Comment by jjchen20** [comment]
I know other faculty have made "hospital medicine" as one of their tags
before. Maybe we could change one of their tags to public.

Would be good to have a way to automatically push tags that we want to be
public so other people can search for them.

**Comment by jjchen20** [comment]
I just retried this by setting "Hospital Medicine" to "public" on the admin end but it does not show up as a pre-set tag in the user interface.

**Comment by razzius** [comment]
Yeah, "public" tags don't work yet. I'll let you know when I get around to that.

**Comment by razzius** [comment]
9751153
