### ISSUE TITLE
Issue with display in faculty profile view

### ISSUE THREAD

**Issue by jjchen20** [razzius/hms-weave#58]
Faculty intended to check all boxes except for shadowing.

This is what shows up in the Browse profiles view:
![image](https://user-images.githubusercontent.com/43801169/51149895-11593080-1832-11e9-9b40-0dd2e13641c3.png)

This is what shows up on the faculty profile:
![image](https://user-images.githubusercontent.com/43801169/51149909-20d87980-1832-11e9-98af-05ebbc93a888.png)

**Comment by jjchen20** [comment]
This is actually happening across the board for all faculty. There's no checkboxes for the first 3 items in the Faculty profile view.

Here's what it looks like in browse profiles:
![image](https://user-images.githubusercontent.com/43801169/51150673-68143980-1835-11e9-9bc3-dd9bf199540b.png)

Here's what it looks like in faculty profile view:
![image](https://user-images.githubusercontent.com/43801169/51150681-6ea2b100-1835-11e9-9bc3-c02b51788725.png)

**Comment by razzius** [comment]
Fixed bbdf30c
