### ISSUE TITLE
Admin view issues: Verification Email

### ISSUE THREAD

**Issue by jjchen20** [razzius/hms-weave#6]

**Comment by jjchen20** [comment]
Enhancement desired: Uploading via direct file upload instead of current url option. Faculty who have trouble uploading themselves are emailing their photos as a file most of the time. For security purposes, files instead of urls is preferred too.

**Comment by razzius** [comment]
I'll make it so that in the admin, users can be designated as admin users and can click "edit profile" from any profile. This will take a decent amount of work. If we need something sooner I'm open to exploring alternative methods.

**Comment by jjchen20** [comment]
Sounds perfect, thanks Razzi. Would this be in the admin interface or
directly in Weave from the browse faculty view?

**Comment by razzius** [comment]
Directly in weave from browse faculty

**Comment by jjchen20** [comment]
Cool, that'd be a great function. Would make it easier to correct typos
right away too.

**Comment by razzius** [comment]
This feature is on staging and needs testing before we roll out to production, though initial tests I've done look promising. Test on https://hms-weave-staging.herokuapp.com/ when you get a chance.

This feature takes 2 steps. First, you have to go to the admin, find your verification_email, set the is_admin to true, and save it.

![image](https://user-images.githubusercontent.com/2244895/51437530-68a53980-1c54-11e9-9ec0-4d3cfcc22e4c.png)

Then, go to the home page and log in using your email. When you browse profiles, you'll see a button that opens the profile you're currently viewing for editing, even if it's not your profile.

![image](https://user-images.githubusercontent.com/2244895/51437461-8aea8780-1c53-11e9-8b82-8747d0f84528.png)

Make your edits, hit preview and save, and it'll be saved.

Your availability checkbox corresponds to your account the entire time. I recommend we don't change users' availability checkboxes but it is possible to edit them directly in the admin.

**Comment by JonKusner** [comment]
Honestly this looks really good. I haven't broken it yet with a number of use cases. This is really powerful but is super helpful for being able to help faculty or control issues.

A small plug for another issue. Now that I see the admin interface having two columns to assign roles I actually don't hate it. It is certainly a clunky way to search through verified emails to try and identify the role of an individual but I don't think we need to restructure the admin interface on that basis. Instead when discussing how to export CSV email lists, we should just make it a step of the export process to specify what list you are trying to generate by checking boxes for mentor, admin, etc... I am realizing now, rather than having students as (-)mentors, there should be a separate category (and column) for medical student. Then we would be able to export on that basis. Let me now what you think (we can also have this discussion in another location).

Really good job with this feature Razzi! It looks really good.

**Comment by jjchen20** [comment]
Hey Razzi, this still isn't working for me. I set myself as an admin and
logging in a couple times but the edit feature isn't showing up. Can you
help see what might be happening?

Jon, I agree about the CSV export lists. I do think it will be important to
have a separate student column, and noting within that column if the
student is a mentee and/or mentor, once we go live with peer mentoring.

**Comment by razzius** [comment]
Ok now it works even if you don't have a profile.

In the process of fixing this I moved some stuff around, so it'd be good to test for regressions on https://hms-weave-staging.herokuapp.com before I deploy everything to production.

**Comment by jjchen20** [comment]
This looks good. I think it's ready for deployment.

**Comment by jjchen20** [comment]
The one comment I have is it'd be best if anything after a comma is not perceived as additional parts of the name. For example, some faculty (and we may eventually require this) include their degree, which is not part of their name. We could separate this as another issue if that would help keep things streamlined.

For Dr. D'Amico's profile below sans photo, we'd want it to say "AD" instead of "ADM."

![image](https://user-images.githubusercontent.com/43801169/51698511-6df9df80-1fd8-11e9-95e2-ad11d30d32ed.png)

**Comment by razzius** [comment]
It's live! Set yourself to an admin and you can now use this in production.

**Comment by jjchen20** [comment]
Razzi, I'm noticing for new sign-ups, the checkboxes in the admin view don't extend down. Can we make sure that the admin option can be extended to future users and that the default is for someone to NOT be an admin if the checkboxes don't show up?

![image](https://user-images.githubusercontent.com/43801169/51793413-46e50e80-218e-11e9-84b9-f28888a810d3.png)

**Comment by jjchen20** [comment]
Can we make a way for admins to see/edit ALL faculty profiles (including hidden ones that are not available for mentoring)?

**Comment by jjchen20** [comment]
Also needed in Admin view: Show both the user name email address (i.e. what was used to access Weave) and the preferred email address (i.e. what's shown on the profile).

**Comment by jjchen20** [comment]
Instead of the verification email number shown here, can we have actual email addresses show up? In the verification email list, there are no numbers, only email addresses. And at the moment, the email address location does not correspond to a counting number, as it can change depending on if any edits are made to the mentor/mentee or admin privileges.

![image](https://user-images.githubusercontent.com/43801169/51809062-723d2b80-226a-11e9-9401-9d095cba1127.png)

**Comment by jjchen20** [comment]
The reason why the <VerificationEmail#> is an issue is because there are faculty whose profile looks like this, and there's no listed email address: 
![image](https://user-images.githubusercontent.com/43801169/54861730-75054b80-4d04-11e9-964f-26035b8e197f.png)

The verification email # above says 435, but there are only 401 unique emails that have accessed Weave, according to the "Verification Email" section: 
![image](https://user-images.githubusercontent.com/43801169/54861736-936b4700-4d04-11e9-8166-4e140ed5fc75.png)

I'm not sure how to interpret the verification email # in this context when the numbers differ and the order of emails change when edits are made to the profile or on user privileges for emails.

**Comment by razzius** [comment]
Verification emails in profile admin now show email

![image](https://user-images.githubusercontent.com/2244895/55780353-9a13f100-5a5c-11e9-95b0-5aaf999057ad.png)

Regarding the number of verification emails versus the verification email id, an implementation detail of our database is that there will be "holes" in the ids, so for example the 100th profile is not guaranteed to have id 100.

**Comment by razzius** [comment]
I think this issue can be closed. It's spanning quite a range of time and website iterations so I recommend opening new issues rather than reopening this one for future ideas.
