### ISSUE TITLE
Ability to "Star" profiles for later

### ISSUE THREAD

**Issue by JonKusner** [razzius/hms-weave#61]
This will likely make more sense once we make a student user portal. My hesitancy with waiting until that time is that I did not want to make students feel like that have to create a profile page in order to get this functionality (if this were they case we could get some students on the list who have no interest in peer-mentoring). I see now that this fear is unfounded because we will just have to be vocal about how to use the on/off toggle (as well as not requiring people to have a published profile to have access to a personal profile portion of the website - the profile generation page which we typically see as being central to a user's personal profile would just be blank [or filled out and toggled off] for those who want the full functions of Weave without wanting to serve as a mentor).

**Comment by razzius** [comment]
Should show star on profile in list view

**Comment by razzius** [comment]
New sorting option "starred profiles first" which then goes alphabetical

**Comment by razzius** [comment]
Tooltip
"Click here to mark the profile as starred"

**Comment by razzius** [comment]
Clicking the star goes from outline to blue, like toggle aethetic

**Comment by razzius** [comment]
This has now been deployed to staging and can be tested!
![image](https://user-images.githubusercontent.com/2244895/78726368-a5576200-78e6-11ea-9759-b094b5330f92.png)

**Comment by jjchen20** [comment]
The star outline looks a little grainy. Can we improve the resolution of the star? It would approve the aesthetic. Functionality and sorting look good!

**Comment by jjchen20** [comment]
Star deployed with SVG
