### ISSUE TITLE
Nested under issue #62. Ability to export sorted registered emails as CSV files.

### ISSUE THREAD

**Issue by JonKusner** [razzius/hms-weave#63]
Once registered emails are sorted by users: faculty vs students vs residents, it would be very helpful for future automated email lists (bumping to see if users want their profile to remain toggle on or off [every 6 months to a year]) to be able to clearly separate which emails apply to what user. I know we currently have this with the mentor checkbox but it will be nice once we have more categories of users to make a more generalizable system by just having new pages for every kind of user.

**Comment by razzius** [comment]
See https://modeanalytics.com/rerere/reports/dff0b26db30c
