### ISSUE TITLE
Suffix shows up in initials

### ISSUE THREAD

**Issue by razzius** [razzius/hms-weave#64]
From #6 

> The one comment I have is it'd be best if anything after a comma is not perceived as additional parts of the name. For example, some faculty (and we may eventually require this) include their degree, which is not part of their name. We could separate this as another issue if that would help keep things streamlined.
> 
> For Dr. D'Amico's profile below sans photo, we'd want it to say "AD" instead of "ADM."
> 
> ![image](https://user-images.githubusercontent.com/43801169/51698511-6df9df80-1fd8-11e9-95e2-ad11d30d32ed.png)
>

**Comment by JonKusner** [comment]
Yeah I agree I think that this is a product of a deeper disorganization that we have on the site. I think we should make a section on the profile generation page that provides checkboxes for individuals to check of their degrees (MD, PhD, MPH, MBA) as well as certifications (FACP, FACC). I was initially reluctant to add this but I think we are introducing more disorganization by leaving it out. The main tipping point for me is also once we have this information in the back end, it is an important step towards expanding to non-MD faculty while also retaining students ability to find MD faculty mentors (we would allow people to narrow searches based on degree). 
We may allow faculty to show or hide this information (I'm not sure about this) but it is certainly data that we should collect. I think our fear in this past was that in making this information mandatorily shown on a profile, do we pressure faculty to provide too formal (or academic) a presentation of themselves; exactly what we have been trying to move away from. Whether or not this data is shown in ones name on the thumbnail or profile is still an open question but I think for a number of reasons this is important data to be collecting.

**Comment by jjchen20** [comment]
Agreed. I could envision a scenario where part of someone's identity could
be being a physician-scientist, and someone may not necessarily put that
down under "Parts of Me" or "Additional Activities" but listing their
degrees could facilitate a student finding them. Same for students who may
be wondering if they should do a MPH, MBA, etc. and seeking advice about
that decision process from someone who has gone down that path.

**Comment by razzius** [comment]
This has been fixed for a while
