### ISSUE TITLE
Student log in directs to faculty log in interface

### ISSUE THREAD

**Issue by jjchen20** [razzius/hms-weave#65]
When I logged in from the student view, it directed me to the faculty log in interface, with the tutorial video present. The student log in view ideally should only say:

Confirm email verification
Successfully logged in as XXX@XXX.edu.

In fact, clicking on "Create profile" links to the faculty profile creation view. Which is not what we want students to be doing.

Clicking on "HMS Weave" at the top then correctly links to the student view.

![image](https://user-images.githubusercontent.com/43801169/51791398-39b92700-2170-11e9-8b11-80f9a62c04fc.png)

**Comment by razzius** [comment]
Fixed in 03b49a93a2408e9e6950a2b08df7e6130cd9b131
