### ISSUE TITLE
Add admin search for emails 

### ISSUE THREAD

**Issue by jjchen20** [razzius/hms-weave#66]
It'd be helpful if the email addresses and profiles were in the same order each time, and don't move when any edits are made (i.e. making an email an admin user). For tracking purposes, it's a bit challenging when emails move around and we lose our place. I just noticed my email moved to the last page when I updated the admin feature.

To help make changes for users more quickly, can we add a search for emails in the "Verification Email" section? That way if someone becomes an admin in the future, in case the order of emails doesn't get maintained, we don't have to go through all the pages to find an email address tucked away on page 14.

**Comment by razzius** [comment]
Pulled ordering into #91

**Comment by razzius** [comment]
![image](https://user-images.githubusercontent.com/2244895/72787504-eb086680-3be4-11ea-8fdd-c1a9a061b842.png)

**Comment by jjchen20** [comment]
This looks good on staging - ready to deploy!
