### ISSUE TITLE
Preview profile freezing

### ISSUE THREAD

**Issue by jjchen20** [razzius/hms-weave#67]
From a faculty mentor: "I am trying to create a profile but it freezes when I make it and hit the preview button. No preview comes up and nothing further happens. Any help?"

The faculty was able to successfully make a profile. Not sure how the issue self-resolved or if he tried a different browser. There was no corresponding Fullstory event at the time that he emailed to report the issue. Could you take a look into this, to make sure the screens are not freezing at any point?

**Comment by jjchen20** [comment]
The faculty experienced the profile freezing in Internet Explorer. "When I redid it, for the 4th time in chrome, it saved. Must be a browser thing."

Can you see if there's a way to improve the Internet Explorer user experience? That is the default browser used in the hospitals. I'll update the Help page with an explanation on recommended browsers in the meantime.

**Comment by razzius** [comment]
Dug into the google analytics data and found that indeed IE accounts for 8% of visitors - 30 in the last month.

![image](https://user-images.githubusercontent.com/2244895/52104716-bb5dea00-25a0-11e9-88c2-b82de03d0017.png)

**Comment by razzius** [comment]
I was able to create a profile using IE 11, but the "parts of me" section would not accept tags :(

**Comment by jjchen20** [comment]
Okay that's unfortunate. I put the workable browsers on the Help page. I am
realizing though that faculty aren't really checking out the Help page.
Most are emailing in that they can't get the website to work. Jon and I can
work on sharing more clearly that Internet Explorer is not a supported
browser.

Do you think the browser compatibility is something HMS IT could fix when
Weave is migrated to Drupal?
