### ISSUE TITLE
Searching by "tags" should search for the entire tag, not individual words in the tag

### ISSUE THREAD

**Issue by jjchen20** [razzius/hms-weave#68]
Running a search for the tag "Family medicine" pulls up faculty who have indicated "Family" and "medicine" separately.

For example: "Family" under Parts of Me and "Adolescent medicine" in clinical interests.

**Comment by jjchen20** [comment]
1) Within a tag, we want to have the whole term come up, i.e. "Family medicine" pulls up "Family medicine" and not "family" and "medicine" separately. 
2) We want to have parts of a word show up across terms, i.e. searching for "onc" or "oncology" should pull up "Radiation oncology," "Medical oncology," "gynecologic oncology," "surgical oncology," etc.

**Comment by razzius** [comment]
Done!
