### ISSUE TITLE
Faculty profile page - build fields for faculty to indicate their degrees

### ISSUE THREAD

**Issue by JonKusner** [razzius/hms-weave#72]
Under the faculty name, there should be a horizontal section of degree checkboxes.
These should include (MD, PhD, MPH, MPP, MBA, MS, MA, other [FACP, FACC, ...])
I will open another issue but these should feed into a conditional search platform.

**Comment by jjchen20** [comment]
Also add: DMD, DDS, DO.

In the browse faculty view, default checked should be MD. Include a "show all" option that unchecks all of the degrees.

**Comment by jjchen20** [comment]
Formatting:

Name
Degrees: MD, PhD, etc. (separated by commas)

**Comment by razzius** [comment]
Here's the first draft of the UI

![image](https://user-images.githubusercontent.com/2244895/54258890-48417f00-4521-11e9-8ec5-8b6a7cae6452.png)

Testable on staging! https://hms-weave-staging.herokuapp.com

**Comment by jjchen20** [comment]
Awesome! One thing I'm noticing is filtering by MD shows the test profile
and filtering by FACP shows the test profile, but filtering on both of
those does not show the test profile. Filtering based on more degree
options should show the union of those degrees ("and" function). Some
people may want to search for a particular combination of degrees (I.e. MD
PhD) and filtering on both MD and PhD should bring up search results for
people who have both of these degrees.

**Comment by razzius** [comment]
Hm ok yeah that's definitely how it's supposed to be working. Probably something relatively simple. I'll look in to it later today.

**Comment by razzius** [comment]
Multiple degree filter works on staging

![image](https://user-images.githubusercontent.com/2244895/54777454-931d5f80-4bcf-11e9-91a5-704ea5e4608c.png)

**Comment by jjchen20** [comment]
Wonderful! I tested out if the free text degrees (i.e. hiiiiii) would be
filterable and it seems like this was not. Which I think is perfectly fine.
This is a huge step - thanks Razzi! Would be cool to see what the admin
backend interface looks like whenever it becomes available.

**Comment by razzius** [comment]
It seems stable to me so I'm deploying to production. If it is worth allowing free text degree filtering, feel free to create an issue. I intend to focus my attention on other features, once I get back to development in a couple weeks

**Comment by razzius** [comment]
I didn't add a backend admin interface. I recommend editing through the ui using the "edit as admin" feature, and searching for degrees to track progress. Building an admin would take a few hours and adding degrees manually would take a comparable amount of time given the number of profiles we have, so I'm declining to implement an admin at least in the immediate term. We can prioritize at a later date.

Since the basic functionality is there, I'm closing this issue.

**Comment by JonKusner** [comment]
Really good work on this Razzi! This is a big step for the platform, thank
you for putting it together and pushing to production!

Best,
Jon
