### ISSUE TITLE
Search function - search conditionally by degrees

### ISSUE THREAD

**Issue by JonKusner** [razzius/hms-weave#73]
Under the search bar there should be a horizontal bar of check boxes (MD, PhD, MPH, MPP, MBA, MS, MA, other [FACP, FACC, ...], **search all**).
MD should be checked by default. If more degrees are checked, the search should be through AND logic.

**Comment by jjchen20** [comment]
Also add: DMD, DDS, DO.

**Comment by jjchen20** [comment]
To complete after issue #72

**Comment by razzius** [comment]
As discussed: if somebody checks MD, PhD - they both have to be there

**Comment by razzius** [comment]
Default MD
Unchecking that shows everybody
