### ISSUE TITLE
Build a way for admin to approve tags and add them to suggested list

### ISSUE THREAD

**Issue by JonKusner** [razzius/hms-weave#77]
#56

**Comment by razzius** [comment]
Also requested: don't show tags with 0 users on search page

**Comment by razzius** [comment]
- Admin for tags
- Load tags when starting server
- Load tags into client (GET /api/settings)

**Comment by razzius** [comment]
At long last! Institutional Affiliations on the profile form now load from the database.

![image](https://user-images.githubusercontent.com/2244895/76694871-601c7900-6635-11ea-93c3-d25918f52c92.png)

![image](https://user-images.githubusercontent.com/2244895/76694875-6ad70e00-6635-11ea-992f-d1240ec46996.png)

Progress so far:

- [x] Institutional Affiliations
- [ ] Clinical Specialties
- [ ] Activities I enjoy

- Parts of me does not have autocomplete, so it is not affected by this feature.
- Degrees has a special case with DDS / DO, so it will be more complex and will be part of a different feature.

**Comment by razzius** [comment]
And they are all done! This can be tested on staging.

**Comment by jjchen20** [comment]
Looks good! Can we delete tags on the back-end? When I tried to delete a tag, I got this error: 
![image](https://user-images.githubusercontent.com/43801169/76915510-f948cb00-6893-11ea-97bf-ad872beb5c60.png)

It would be helpful for the admin to be able to delete/merge redundant tags like "first generation" and "First-Generation."

**Comment by razzius** [comment]
Currently, you can only delete tags if there are no associated profiles, so the easiest way would be to edit a profile as admin, update the tag to the preferred one, then delete the old tag in the backend. We can create a better admin interface that would allow this.

**Comment by razzius** [comment]
Created a new issue to track that: https://github.com/razzius/hms-weave/issues/177
