### ISSUE TITLE
Remove extra space at bottom of this list as a selectable option

### ISSUE THREAD

**Issue by jjchen20** [razzius/hms-weave#79]
![image](https://user-images.githubusercontent.com/43801169/53592044-714a3300-3b63-11e9-958f-71706942eec1.png)

**Comment by jjchen20** [comment]
Shows up as a blank space when selected:
![image](https://user-images.githubusercontent.com/43801169/53592105-8f179800-3b63-11e9-9a3e-26bb58b86a5f.png)

**Comment by razzius** [comment]
Whoops that was silly of me
