### ISSUE TITLE
Allow users to sort the entire list of faculty or search results by "Most recent" or "Alphabetical"

### ISSUE THREAD

**Issue by jjchen20** [razzius/hms-weave#83]
![image](https://user-images.githubusercontent.com/43801169/54794273-fb466280-4c1c-11e9-90fe-387e12e8693d.png)

**Comment by razzius** [comment]
This has been deployed but somehow reverse alphabetical is the default, when what we want is date updated. Looking into it.

**Comment by razzius** [comment]
Fixed!
