### ISSUE TITLE
Allow users to filter results by institutional affiliations

### ISSUE THREAD

**Issue by jjchen20** [razzius/hms-weave#84]
Hospital affiliations:
[ ] Beth Israel Deaconess Medical Center
[ ] Boston Children's Hospital
[ ] Brigham and Women's Hospital
[ ] Broad Institute
[ ] Cambridge Health Alliance
[ ] Dana-Farber Cancer Institute
[ ] Forsyth Institute
[ ] Harvard Pilgrim Health Care
[ ] Hebrew SeniorLife
[ ] Joslin Diabetes Center
[ ] Judge Baker Children’s Center
[ ] Massachusetts Eye and Ear Infirmary
[ ] Massachusetts General Hospital
[ ] McLean Hospital
[ ] Mount Auburn Hospital
[ ] Schepens Eye Research Institute
[ ] Spaulding Rehabilitation Hospital
[ ] Veterans Affairs Boston Healthcare System
[ ] Wyss Institute

**Comment by jjchen20** [comment]
#87 Add the following two options:
[ ] Harvard Medical School Quad
[ ] Harvard School of Dental Medicine

**Comment by razzius** [comment]
Testable on staging

**Comment by razzius** [comment]
Done
