### ISSUE TITLE
Show degrees on profile thumbnail

### ISSUE THREAD

**Issue by JonKusner** [razzius/hms-weave#85]
Once an individual specifies their degrees we shouldhave some way for them to show from the thumbnail. This will allow us to make names much more consistent (taking degrees and titles out of the "Name" field).

I am in favor of not having a title section that says "degrees" on the thumbnail but rather have the degrees follow the name in-line, comma separated, in a lighter font color than straight #000000 black like the name is. This will still communicate the information but will visually emphasize the mentor's name (we would have to play around with the exact shade, to optimize readability while still having this name-preference effect).

A question I have is whether this styling should continue into the profile page, in addition to the "Degrees" field.

**Comment by razzius** [comment]
![image](https://user-images.githubusercontent.com/2244895/56326194-ebda0c80-6129-11e9-98e4-4907252a08e5.png)

Could look like that

**Comment by razzius** [comment]
Could also play with the font size (this is 85%)
![image](https://user-images.githubusercontent.com/2244895/56326223-0f04bc00-612a-11e9-94f7-8fd8d24aca6b.png)

**Comment by razzius** [comment]
Combination no comma and 85% font

![image](https://user-images.githubusercontent.com/2244895/56326310-5be89280-612a-11e9-8626-1a7688623d67.png)

Any of these combinations are doable. Deploying 100% font size with comma to staging (first screenshot)

**Comment by JonKusner** [comment]
My vote is for the second of these three options: Font 85% with comma. I think the gray looks excellent!

**Comment by jjchen20** [comment]
Agreed, the gray and commas at 100% look excellent! Can we maintain the degrees in the order that faculty input them? For example, some faculty may be particular about MD, PhD, or another order for their degrees.

**Comment by razzius** [comment]
Done
