### ISSUE TITLE
Institutional Affiliations: Add "Harvard Medical School Quad" and "Harvard School of Dental Medicine"

### ISSUE THREAD

**Issue by jjchen20** [razzius/hms-weave#87]
1) Rename "Hospital Affiliations" to "Institutional Affiliations."
2) Under Institutional Affiliations, add "Harvard Medical School Quad" and "Harvard School of Dental Medicine" for basic science faculty and dental faculty, respectively.

**Comment by razzius** [comment]
Done

Soon to do: admin interface to edit these options and others so we don't have to create issues to update them, and so that the platform is more generalizable.

**Comment by jjchen20** [comment]
I just tested this out and it looks perfect! I'll connect with the
coordinator for dental faculty roll-out before Monday.
