### ISSUE TITLE
Ordering for admin

### ISSUE THREAD

**Issue by razzius** [razzius/hms-weave#91]
Order by PK

**Comment by razzius** [comment]
Turns out by clicking on a header you can control the ordering

![image](https://user-images.githubusercontent.com/2244895/56397475-b9e3ab80-61f8-11e9-96a1-a1e244f53c0f.png)

Still, I added default ordering for all admin pages. Some are by date created, 1 by id: `VerificationEmail`, and some by value (tags).

**Comment by jjchen20** [comment]
So we can keep track of the ordering, is it like this:
- Verification Email: by ID number
- Profile: by date of profile creation
- Tags: by value
