### ISSUE TITLE
"DMD / DDS" should show profiles with DMD or DDS

### ISSUE THREAD

**Issue by razzius** [razzius/hms-weave#96]
Profiles still want to be able to differentiate

**Comment by jjchen20** [comment]
Same issue as with MD/DO. The filter results should include everyone who has a DMD and everyone who has a DDS degree.

![image](https://user-images.githubusercontent.com/43801169/64207663-17f0f280-ce6b-11e9-82ea-2730e1a81862.png)

**Comment by razzius** [comment]
Should be fixex
