### ISSUE TITLE
MD / DO should show profiles with MD and DO

### ISSUE THREAD

**Issue by razzius** [razzius/hms-weave#97]
Similar to #96, individual profiles can show this

**Comment by jjchen20** [comment]
Faculty will have either an MD or DO degree (not both). The tag MD/DO should pull up everyone who designates MD on their profiles, and everyone who designates DO on their profiles.

As the code is written now, there are zero search results for MD/DO:

![image](https://user-images.githubusercontent.com/43801169/64207544-d95b3800-ce6a-11e9-9444-5e3ee94bdc49.png)

**Comment by razzius** [comment]
Fixed
