### ISSUE TITLE
Query to tabulate tallies for verification tokens

### ISSUE THREAD

**Issue by jjchen20** [razzius/hms-weave#98]
Query for (from September 1, 2018 to April 30, 2019): 
- Total number of log-ins for all mentors
- Total number of log-ins for all mentees
- Average number of log-ins per mentor
- Average number of log-ins per mentee
- Top 5 number of log-ins for mentors (i.e. Mentor A logged in 16 times, Mentor B logged in 10 times, Mentor C logged in 8 times, etc.)
- Top 5 number of log-ins for mentees (i.e. Mentee A logged in 20 times, etc.)

Desired deadline for query results: June 28, 2019

**Comment by razzius** [comment]
```
SELECT count(token.date_created),
       email.email,
       bool_and(email.is_mentor) as "is mentor"
FROM public.verification_token token
JOIN public.verification_email email
  ON token.email_id = email.id
  group by email.email
  order by count desc
```

**Comment by razzius** [comment]
Here's the query for average visits (change WHERE clause at the end to toggle mentor / not mentor), not counting ourselves

```sql
with stats AS
  (SELECT count(token.date_created) AS c,
          email.email,
          bool_and(email.is_mentor) AS "is mentor"
   FROM public.verification_token token
   JOIN public.verification_email email
     ON token.email_id = email.id
   WHERE email.email not in ('razzi@hmsweave.com',
                             'jiejane_chen@hms.harvard.edu',
                             'jonathan_kusner@hms.harvard.edu',
                             'testrazzi@hmsweave.com')
   GROUP BY email.email
   ORDER BY c DESC)
SELECT sum(c)/count(c) AS avg_mentee_logins
FROM stats
WHERE stats."is mentor" = false
```

**Comment by razzius** [comment]
Data has been sent

Report is at https://modeanalytics.com/editor/rerere/reports/e97054f87269
