### ISSUE TITLE
Change website title from "HMS Weave" to "Weave" and edit About section

### ISSUE THREAD

**Issue by jjchen20** [razzius/hms-weave#99]
To be more inclusive of HSDM. Would ideally add the HMS and HSDM crests/ logos. Will reach out to communications office for clearance.

**Comment by jjchen20** [comment]
Soon after entering medical school and dental school, students are faced with a new learning and social environment and pressure to quickly determine academic or clinical interests. Although resources for faculty contact information exist, both students and faculty have found there to be unclear expectations about what a mentorship relationship or experience will constitute. Furthermore, for students with myriad interests who are still in the process of discovering their desired field of medicine, it is often challenging to know who to reach out to when lists of faculty members are provided solely based on clinical specialty.

We developed a mentorship platform that provides an interest-driven way for students to find invested mentors for professional or personal guidance. In recognizing that students can only set expectations for their side of the mentoring relationship, our platform will allow faculty to more clearly communicate their own level of comfort in engaging in a mentoring relationship. In recognizing that many clinical, academic, and personal demands exist for faculty, we hope to empower faculty to articulate for themselves what their level of mentorship involvement will be.

On this platform, faculty may personalize their profiles, including sharing a preferred cadence for meeting with students, indicating topics that they are willing to discuss, and showing or hiding their profiles based on their availability. Students may search for mentors using both clinical and non-clinical “tags,” as well as view available faculty profiles. In each profile, students will see additional opportunities that each faculty offers and other preferences that faculty members have chosen for themselves.

We hope that this mentorship platform provides an opt-in, customized mentoring structure with clear, adjustable expectations for both mentors and mentees that may encourage more longitudinal and meaningful mentoring experiences.

If you are passionate about improving mentoring at Harvard Medical School and Harvard School of Dental Medicine or at similar institutions, we would love to hear from you! Please reach out to us at: weave@hms.harvard.edu

**Comment by razzius** [comment]
Done in e476563e9a6a8aa9bbbfdfc88d1da06590c128d1
